### ISSUE TITLE
provides no component of type apoli:powers crash

### ISSUE THREAD

**Issue by Lhruggles** [apace100/apoli#32] opened 2021-12-21 19:03 UTC
ive tried getting the command to not affect items, but it keeps trying to assign powers to items causing a crash
[crash-2021-12-21_12.52.26-client.txt](https://github.com/apace100/apoli/files/7757451/crash-2021-12-21_12.52.26-client.txt)

**Comment by eggohito** [comment] 2023-07-18 14:24
This is caused by using either the `power` or `resource` entity condition types without using the `living` entity condition type beforehand. This should now be fixed in [Apoli v2.9.0](https://github.com/apace100/apoli/releases/tag/v2.9.0)

**Closed by eggohito** 2023-07-18 14:24 UTC
