### ISSUE TITLE
[1.20.1] `replace_loot_table` power type is causing game crash.

### ISSUE THREAD

**Issue by Reniel80** [apace100/apoli#221] opened 2024-05-04 18:58 UTC
Is planned any backport or update for Origins/Apoli 1.20.1 to fix this issue?

This is one of the most used versions due to the large number of amazing and available mods and datapacks that have not been ported to 1.20.2+

Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "id" is null
	at io.github.apace100.apoli.power.ReplaceLootTablePower.hasReplacement(ReplaceLootTablePower.java:58)
	at net.minecraft.class_52.md806bce$apoli$lambda$modifyLootTable$0$0(class_52.java:578)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at net.minecraft.class_52.handler$zcb000$apoli$modifyLootTable(class_52.java:580)
	at net.minecraft.class_52.method_328(class_52.java)
	at net.minecraft.class_52.method_51880(class_52.java:95)
	at net.minecraft.class_1309.method_16077(class_1309.java:1453)
	at net.minecraft.class_1308.method_16077(class_1308.java:512)
	at net.minecraft.class_1309.method_16080(class_1309.java:1410)
	at net.minecraft.class_1309.method_6078(class_1309.java:1366)
	at net.minecraft.class_1309.method_5643(class_1309.java:1222)
	at net.minecraft.class_1429.method_5643(class_1429.java:81)
	at net.minecraft.class_1665.method_7454(class_1665.java:374)
	at net.minecraft.class_1676.method_7488(class_1676.java:153)
	at net.minecraft.class_1665.method_5773(class_1665.java:227)
	at net.minecraft.class_1667.method_5773(class_1667.java:104)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.apace100.apoli.power.ReplaceLootTablePower.hasReplacement(ReplaceLootTablePower.java:58)
	at net.minecraft.class_52.md806bce$apoli$lambda$modifyLootTable$0$0(class_52.java:578)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at net.minecraft.class_52.handler$zcb000$apoli$modifyLootTable(class_52.java:580)
	at net.minecraft.class_52.method_328(class_52.java)
	at net.minecraft.class_52.method_51880(class_52.java:95)
	at net.minecraft.class_1309.method_16077(class_1309.java:1453)
	at net.minecraft.class_1308.method_16077(class_1308.java:512)
	at net.minecraft.class_1309.method_16080(class_1309.java:1410)
	at net.minecraft.class_1309.method_6078(class_1309.java:1366)
	at net.minecraft.class_1309.method_5643(class_1309.java:1222)
	at net.minecraft.class_1429.method_5643(class_1429.java:81)
	at net.minecraft.class_1665.method_7454(class_1665.java:374)
	at net.minecraft.class_1676.method_7488(class_1676.java:153)
	at net.minecraft.class_1665.method_5773(class_1665.java:227)
	at net.minecraft.class_1667.method_5773(class_1667.java:104)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: minecraft:arrow (net.minecraft.class_1667)
	Entity ID: 185
	Entity Name: Flecha
	Entity's Exact location: 9.22, -59.58, -13.55
	Entity's Block location: World: (9,-60,-14), Section: (at 9,4,2 in 0,-4,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 2.23, -1.14, 1.55
	Entity's Passengers: []
	Entity's Vehicle: null

**Comment by eggohito** [comment] 2024-05-05 06:44
Closing as duplicate of https://github.com/apace100/apoli/issues/178

**Closed as not planned by eggohito** 2024-05-05 06:44 UTC
Labels: duplicate
