### ISSUE TITLE
[1.20.1] LivingEntityMixin.updateItemStackHolder is called every tick on every entity

### ISSUE THREAD

**Issue by Martmists-GH** [apace100/apoli#236] opened 2024-06-18 18:23 UTC
This leads to very poor performance every tick; It's causing watchdog kills on many servers, especially with many players.

**Comment by eggohito** [comment] 2024-06-18 19:29
Duplicate of #216 (See https://github.com/apace100/apoli/issues/216#issuecomment-2067707737 for more info)

**Closed as not planned by eggohito** 2024-06-18 19:29 UTC
