### ISSUE TITLE
Adding an Entity Type Tags using Powers

### ISSUE THREAD

**Issue by 256smash** [apace100/apoli#213] opened 2024-03-31 14:23 UTC
In vanilla minecraft, there are tags in the datapack that affect vanilla mob abilities such as stray which uses "freeze_immune_entity_types" and "skeletons". These entity type tags can be used as powers so the datapack doesn't have to be changed again, for example a player can get the "freeze_hurts_extra_types" tag for themselves and other players and mobs that this can be used for origin.

**Comment by ChrysanthCow** [comment] 2024-04-01 04:35
This is a planned feature for the next update.

Duplicate of https://github.com/apace100/apoli/issues/203

**Closed as completed** 2024-04-01 23:02 UTC
